/**
 * TeSS API
 * Access, search and filter through collections of training materials, events, packages, and workflows in TeSS. As a rule of thumb - You can add .json to the end of most pages to retrieve the data in a common exchange format. e.g - https://tess.elixir-europe.org/events/software-carpentry-west-virginia-university.json - https://tess.elixir-europe.org/materials/rna-seq-de-novo-transcriptome-reconstruction-with-rna-seq.json - https://tess.elixir-europe.org/packages/biocomp-computing-skills-collection.json - https://tess.elixir-europe.org/workflows/das-internet-fur-biologen.json - https://tess.elixir-europe.org/nodes/united-kingdom.json
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Event', 'model/ExternalResource', 'model/Material', 'model/ScientificTopic', 'model/ShortEvent', 'model/ShortMaterial', 'api/EventsApi', 'api/MaterialsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Event'), require('./model/ExternalResource'), require('./model/Material'), require('./model/ScientificTopic'), require('./model/ShortEvent'), require('./model/ShortMaterial'), require('./api/EventsApi'), require('./api/MaterialsApi'));
  }
}(function(ApiClient, Event, ExternalResource, Material, ScientificTopic, ShortEvent, ShortMaterial, EventsApi, MaterialsApi) {
  'use strict';

  /**
   * Access_search_and_filter_through_collections_of_training_materials_events_packages_and_workflows_in_TeSS_As_a_rule_of_thumb___You_can_add__json_to_the_end_of_most_pages_to_retrieve_the_data_in_a_common_exchange_format__e_g__httpstess_elixir_europe_orgeventssoftware_carpentry_west_virginia_university_json__httpstess_elixir_europe_orgmaterialsrna_seq_de_novo_transcriptome_reconstruction_with_rna_seq_json__httpstess_elixir_europe_orgpackagesbiocomp_computing_skills_collection_json__httpstess_elixir_europe_orgworkflowsdas_internet_fur_biologen_json__httpstess_elixir_europe_orgnodesunited_kingdom_json.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var TeSsApi = require('index'); // See note below*.
   * var xxxSvc = new TeSsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new TeSsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new TeSsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new TeSsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event: Event,
    /**
     * The ExternalResource model constructor.
     * @property {module:model/ExternalResource}
     */
    ExternalResource: ExternalResource,
    /**
     * The Material model constructor.
     * @property {module:model/Material}
     */
    Material: Material,
    /**
     * The ScientificTopic model constructor.
     * @property {module:model/ScientificTopic}
     */
    ScientificTopic: ScientificTopic,
    /**
     * The ShortEvent model constructor.
     * @property {module:model/ShortEvent}
     */
    ShortEvent: ShortEvent,
    /**
     * The ShortMaterial model constructor.
     * @property {module:model/ShortMaterial}
     */
    ShortMaterial: ShortMaterial,
    /**
     * The EventsApi service constructor.
     * @property {module:api/EventsApi}
     */
    EventsApi: EventsApi,
    /**
     * The MaterialsApi service constructor.
     * @property {module:api/MaterialsApi}
     */
    MaterialsApi: MaterialsApi
  };

  return exports;
}));
